File : ./data_new.txt is in split mode.
Please run at project root: "python3 file_split_merge.py --merge" 